// Copyright (c) 2025 ADBC Drivers Contributors
//
// This file has been modified from its original version, which is
// under the Apache License:
//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Vendored from upstream go/adbc/driver/internal

package driverbase

import (
	"context"
	"fmt"
	"regexp"
	"strings"

	"github.com/apache/arrow-adbc/go/adbc"
	"github.com/apache/arrow-go/v18/arrow"
	"github.com/apache/arrow-go/v18/arrow/array"
	"github.com/apache/arrow-go/v18/arrow/memory"
	"go.opentelemetry.io/otel/codes"
	semconv "go.opentelemetry.io/otel/semconv/v1.30.0"
	"go.opentelemetry.io/otel/trace"
)

// Constants for names of constraint types
const (
	Check      = "CHECK"
	ForeignKey = "FOREIGN KEY"
	PrimaryKey = "PRIMARY KEY"
	Unique     = "UNIQUE"
)

var (
	AcceptAll = regexp.MustCompile(".*")
)

// Helper function that compiles a SQL-style pattern (%, _) to a regex
func PatternToRegexp(pattern *string) (*regexp.Regexp, error) {
	if pattern == nil {
		return nil, nil
	}

	var builder strings.Builder
	if _, err := builder.WriteString("(?i)^"); err != nil {
		return nil, err
	}
	for _, c := range *pattern {
		switch {
		case c == rune('_'):
			if _, err := builder.WriteString("."); err != nil {
				return nil, err
			}
		case c == rune('%'):
			if _, err := builder.WriteString(".*"); err != nil {
				return nil, err
			}
		default:
			if _, err := builder.WriteString(regexp.QuoteMeta(string([]rune{c}))); err != nil {
				return nil, err
			}
		}
	}
	if _, err := builder.WriteString("$"); err != nil {
		return nil, err
	}
	return regexp.Compile(builder.String())
}

const (
	COLUMN_NAME                 = "COLUMN_NAME"
	ORDINAL_POSITION            = "ORDINAL_POSITION"
	REMARKS                     = "REMARKS"
	XDBC_DATA_TYPE              = "XDBC_DATA_TYPE"
	XDBC_TYPE_NAME              = "XDBC_TYPE_NAME"
	XDBC_COLUMN_SIZE            = "XDBC_COLUMN_SIZE"
	XDBC_DECIMAL_DIGITS         = "XDBC_DECIMAL_DIGITS"
	XDBC_NUM_PREC_RADIX         = "XDBC_NUM_PREC_RADIX"
	XDBC_NULLABLE               = "XDBC_NULLABLE"
	XDBC_COLUMN_DEF             = "XDBC_COLUMN_DEF"
	XDBC_SQL_DATA_TYPE          = "XDBC_SQL_DATA_TYPE"
	XDBC_DATETIME_SUB           = "XDBC_DATETIME_SUB"
	XDBC_CHAR_OCTET_LENGTH      = "XDBC_CHAR_OCTET_LENGTH"
	XDBC_IS_NULLABLE            = "XDBC_IS_NULLABLE"
	XDBC_SCOPE_CATALOG          = "XDBC_SCOPE_CATALOG"
	XDBC_SCOPE_SCHEMA           = "XDBC_SCOPE_SCHEMA"
	XDBC_SCOPE_TABLE            = "XDBC_SCOPE_TABLE"
	XDBC_IS_AUTOINCREMENT       = "XDBC_IS_AUTOINCREMENT"
	XDBC_IS_AUTOGENERATEDCOLUMN = "XDBC_IS_AUTOGENERATEDCOLUMN"
)

// The JDBC/ODBC-defined type of any object.
// All the values here are the sames as in the JDBC and ODBC specs.
type XdbcDataType int32

const (
	XdbcDataType_XDBC_UNKNOWN_TYPE  XdbcDataType = 0
	XdbcDataType_XDBC_CHAR          XdbcDataType = 1
	XdbcDataType_XDBC_NUMERIC       XdbcDataType = 2
	XdbcDataType_XDBC_DECIMAL       XdbcDataType = 3
	XdbcDataType_XDBC_INTEGER       XdbcDataType = 4
	XdbcDataType_XDBC_SMALLINT      XdbcDataType = 5
	XdbcDataType_XDBC_FLOAT         XdbcDataType = 6
	XdbcDataType_XDBC_REAL          XdbcDataType = 7
	XdbcDataType_XDBC_DOUBLE        XdbcDataType = 8
	XdbcDataType_XDBC_DATETIME      XdbcDataType = 9
	XdbcDataType_XDBC_INTERVAL      XdbcDataType = 10
	XdbcDataType_XDBC_VARCHAR       XdbcDataType = 12
	XdbcDataType_XDBC_DATE          XdbcDataType = 91
	XdbcDataType_XDBC_TIME          XdbcDataType = 92
	XdbcDataType_XDBC_TIMESTAMP     XdbcDataType = 93
	XdbcDataType_XDBC_LONGVARCHAR   XdbcDataType = -1
	XdbcDataType_XDBC_BINARY        XdbcDataType = -2
	XdbcDataType_XDBC_VARBINARY     XdbcDataType = -3
	XdbcDataType_XDBC_LONGVARBINARY XdbcDataType = -4
	XdbcDataType_XDBC_BIGINT        XdbcDataType = -5
	XdbcDataType_XDBC_TINYINT       XdbcDataType = -6
	XdbcDataType_XDBC_BIT           XdbcDataType = -7
	XdbcDataType_XDBC_WCHAR         XdbcDataType = -8
	XdbcDataType_XDBC_WVARCHAR      XdbcDataType = -9
)

func ToXdbcDataType(dt arrow.DataType) (xdbcType XdbcDataType) {
	if dt == nil {
		return XdbcDataType_XDBC_UNKNOWN_TYPE
	}

	switch dt.ID() {
	case arrow.EXTENSION:
		return ToXdbcDataType(dt.(arrow.ExtensionType).StorageType())
	case arrow.DICTIONARY:
		return ToXdbcDataType(dt.(*arrow.DictionaryType).ValueType)
	case arrow.RUN_END_ENCODED:
		return ToXdbcDataType(dt.(*arrow.RunEndEncodedType).Encoded())
	case arrow.INT8, arrow.UINT8:
		return XdbcDataType_XDBC_TINYINT
	case arrow.INT16, arrow.UINT16:
		return XdbcDataType_XDBC_SMALLINT
	case arrow.INT32, arrow.UINT32:
		return XdbcDataType_XDBC_INTEGER
	case arrow.INT64, arrow.UINT64:
		return XdbcDataType_XDBC_BIGINT
	case arrow.FLOAT32, arrow.FLOAT16, arrow.FLOAT64:
		return XdbcDataType_XDBC_FLOAT
	case arrow.DECIMAL, arrow.DECIMAL256:
		return XdbcDataType_XDBC_DECIMAL
	case arrow.STRING, arrow.LARGE_STRING:
		return XdbcDataType_XDBC_VARCHAR
	case arrow.BINARY, arrow.LARGE_BINARY:
		return XdbcDataType_XDBC_BINARY
	case arrow.FIXED_SIZE_BINARY:
		return XdbcDataType_XDBC_BINARY
	case arrow.BOOL:
		return XdbcDataType_XDBC_BIT
	case arrow.TIME32, arrow.TIME64:
		return XdbcDataType_XDBC_TIME
	case arrow.DATE32, arrow.DATE64:
		return XdbcDataType_XDBC_DATE
	case arrow.TIMESTAMP:
		return XdbcDataType_XDBC_TIMESTAMP
	case arrow.DENSE_UNION, arrow.SPARSE_UNION:
		return XdbcDataType_XDBC_VARBINARY
	case arrow.LIST, arrow.LARGE_LIST, arrow.FIXED_SIZE_LIST:
		return XdbcDataType_XDBC_VARBINARY
	case arrow.STRUCT, arrow.MAP:
		return XdbcDataType_XDBC_VARBINARY
	default:
		return XdbcDataType_XDBC_UNKNOWN_TYPE
	}
}

// Starts a trace.Span with the given spanName for the tracing object with
// the given ctx context.
func StartSpan(ctx context.Context, spanName string, tracing adbc.OTelTracing, opts ...trace.SpanStartOption) (context.Context, trace.Span) {
	if tracing == nil {
		return ctx, trace.SpanFromContext(ctx)
	}

	attrs := tracing.GetInitialSpanAttributes()
	attrs = append(attrs, semconv.DBOperationName(spanName))
	opts = append(opts, trace.WithAttributes(attrs...))

	return tracing.StartSpan(ctx, spanName, opts...)
}

// Ends the given span. If err is not nil, then the
// error is recorded and the status is set appropriately.
// Otherwise, the status is set to Ok.
func EndSpan(span trace.Span, err error, options ...trace.SpanEndOption) {
	if err != nil {
		span.RecordError(err)
		if adbcError, ok := err.(adbc.Error); ok {
			span.SetAttributes(semconv.ErrorTypeKey.String(adbcError.Code.String()))
		}
		span.SetStatus(codes.Error, err.Error())
	} else {
		span.SetStatus(codes.Ok, "")
	}
	span.End(options...)
}

// GetStatistics and GetStatisticNames helpers

// Union type codes for ADBC GetStatistics statistic_value dense union.
// These map to the union type codes defined in adbc.GetStatisticsSchema:
//   - 0: int64 (exact counts, exact statistics)
//   - 1: uint64 (large exact counts)
//   - 2: float64 (approximate counts, approximate statistics)
//   - 3: binary (encoded data like timestamps, complex values)
const (
	UnionTypeInt64   arrow.UnionTypeCode = 0
	UnionTypeUint64  arrow.UnionTypeCode = 1
	UnionTypeFloat64 arrow.UnionTypeCode = 2
	UnionTypeBinary  arrow.UnionTypeCode = 3
)

// Statistic represents a single statistic value for a table or column.
// This struct is used to accumulate statistics before building the final
// Arrow RecordReader for GetStatistics results.
//
// Per ADBC v1.1.0 spec (adbc.h), certain statistics have type requirements:
//   - row_count: int64 (when not approximate) or float64 (when approximate)
//   - null_count: int64 (when not approximate) or float64 (when approximate)
//
// All other statistics can use any of the union types based on their natural type.
type Statistic struct {
	TableName  string
	ColumnName *string // nil for table-level statistics
	Key        int16
	ValueKind  arrow.UnionTypeCode
	ValueI64   int64
	ValueU64   uint64
	ValueF64   float64
	ValueBin   []byte
	Approx     bool
}

// NewInt64Stat creates a statistic with an int64 value.
// Use this for exact integer statistics (e.g., exact row counts, exact null counts).
func NewInt64Stat(table string, column *string, key int16, value int64, approx bool) Statistic {
	return Statistic{
		TableName:  table,
		ColumnName: column,
		Key:        key,
		ValueKind:  UnionTypeInt64,
		ValueI64:   value,
		Approx:     approx,
	}
}

// NewUint64Stat creates a statistic with a uint64 value.
// Use this for large exact unsigned integer statistics.
func NewUint64Stat(table string, column *string, key int16, value uint64, approx bool) Statistic {
	return Statistic{
		TableName:  table,
		ColumnName: column,
		Key:        key,
		ValueKind:  UnionTypeUint64,
		ValueU64:   value,
		Approx:     approx,
	}
}

// NewFloat64Stat creates a statistic with a float64 value.
// Use this for approximate numeric statistics (e.g., approximate row counts, approximate null counts).
// Per ADBC spec, row_count and null_count MUST use float64 when approximate=true.
func NewFloat64Stat(table string, column *string, key int16, value float64, approx bool) Statistic {
	return Statistic{
		TableName:  table,
		ColumnName: column,
		Key:        key,
		ValueKind:  UnionTypeFloat64,
		ValueF64:   value,
		Approx:     approx,
	}
}

// NewBinaryStat creates a statistic with a binary value.
// Use this for encoded data like timestamps (RFC3339), JSON, or complex values.
func NewBinaryStat(table string, column *string, key int16, value []byte, approx bool) Statistic {
	return Statistic{
		TableName:  table,
		ColumnName: column,
		Key:        key,
		ValueKind:  UnionTypeBinary,
		ValueBin:   value,
		Approx:     approx,
	}
}

// EmptyGetStatisticsReader returns an empty GetStatistics result.
// This is useful when no statistics are available for the requested filters.
func EmptyGetStatisticsReader(alloc memory.Allocator) (array.RecordReader, error) {
	bldr := array.NewRecordBuilder(alloc, adbc.GetStatisticsSchema)
	defer bldr.Release()

	rec := bldr.NewRecordBatch()
	defer rec.Release()

	return array.NewRecordReader(adbc.GetStatisticsSchema, []arrow.RecordBatch{rec})
}

// BuildGetStatisticsReader constructs an Arrow RecordReader from pre-computed statistics.
// This function handles the complex nested Arrow structure required by ADBC GetStatistics.
//
// Parameters:
//   - alloc: Memory allocator for Arrow builders
//   - catalogOrder: List of catalog names in order
//   - schemaOrder: Map of catalog name to ordered list of schema names
//   - statsByCatalog: Map of catalog -> schema -> statistics list
//
// The function builds the nested structure:
//
//	catalog_name: string
//	catalog_db_schemas: list<struct{
//	    db_schema_name: string
//	    db_schema_statistics: list<struct{
//	        table_name: string
//	        column_name: string (nullable)
//	        statistic_key: int16
//	        statistic_value: dense_union<int64, uint64, float64, binary>
//	        statistic_is_approximate: bool
//	    }>
//	}>
func BuildGetStatisticsReader(
	alloc memory.Allocator,
	catalogOrder []string,
	schemaOrder map[string][]string,
	statsByCatalog map[string]map[string][]Statistic,
) (array.RecordReader, error) {
	bldr := array.NewRecordBuilder(alloc, adbc.GetStatisticsSchema)
	defer bldr.Release()

	// Get all field builders
	catalogNameBldr := bldr.Field(0).(*array.StringBuilder)
	catalogSchemasBldr := bldr.Field(1).(*array.ListBuilder)
	dbSchemaStructBldr := catalogSchemasBldr.ValueBuilder().(*array.StructBuilder)
	dbSchemaNameBldr := dbSchemaStructBldr.FieldBuilder(0).(*array.StringBuilder)
	dbSchemaStatsListBldr := dbSchemaStructBldr.FieldBuilder(1).(*array.ListBuilder)

	statsStructBldr := dbSchemaStatsListBldr.ValueBuilder().(*array.StructBuilder)
	tableNameBldr := statsStructBldr.FieldBuilder(0).(*array.StringBuilder)
	columnNameBldr := statsStructBldr.FieldBuilder(1).(*array.StringBuilder)
	statKeyBldr := statsStructBldr.FieldBuilder(2).(*array.Int16Builder)
	statValueBldr := statsStructBldr.FieldBuilder(3).(*array.DenseUnionBuilder)
	statApproxBldr := statsStructBldr.FieldBuilder(4).(*array.BooleanBuilder)

	statI64Bldr := statValueBldr.Child(0).(*array.Int64Builder)
	statU64Bldr := statValueBldr.Child(1).(*array.Uint64Builder)
	statF64Bldr := statValueBldr.Child(2).(*array.Float64Builder)
	statBinBldr := statValueBldr.Child(3).(*array.BinaryBuilder)

	// Build Arrow structure from pre-computed statistics
	for _, catalogName := range catalogOrder {
		catalogNameBldr.Append(catalogName)
		catalogSchemasBldr.Append(true)

		for _, schema := range schemaOrder[catalogName] {
			dbSchemaStructBldr.Append(true)
			dbSchemaNameBldr.Append(schema)
			dbSchemaStatsListBldr.Append(true)

			for _, st := range statsByCatalog[catalogName][schema] {
				statsStructBldr.Append(true)
				tableNameBldr.Append(st.TableName)

				if st.ColumnName == nil {
					columnNameBldr.AppendNull()
				} else {
					columnNameBldr.Append(*st.ColumnName)
				}

				statKeyBldr.Append(st.Key)
				statApproxBldr.Append(st.Approx)

				statValueBldr.Append(st.ValueKind)
				switch st.ValueKind {
				case UnionTypeInt64:
					statI64Bldr.Append(st.ValueI64)
				case UnionTypeUint64:
					statU64Bldr.Append(st.ValueU64)
				case UnionTypeFloat64:
					statF64Bldr.Append(st.ValueF64)
				case UnionTypeBinary:
					statBinBldr.Append(st.ValueBin)
				default:
					return nil, adbc.Error{
						Code: adbc.StatusInternal,
						Msg:  fmt.Sprintf("unknown statistic value kind: %d", st.ValueKind),
					}
				}
			}
		}
	}

	rec := bldr.NewRecordBatch()
	defer rec.Release()

	return array.NewRecordReader(adbc.GetStatisticsSchema, []arrow.RecordBatch{rec})
}

// StatisticNameKey represents a named statistic with its key for GetStatisticNames.
type StatisticNameKey struct {
	Name string
	Key  int16
}

// BuildGetStatisticNamesReader constructs an Arrow RecordReader for GetStatisticNames.
// Returns driver-specific statistics (keys >= 1024) in name/key pairs.
// Pass nil or empty slice to return an empty result (e.g., for drivers with no custom statistics).
func BuildGetStatisticNamesReader(
	alloc memory.Allocator,
	statistics []StatisticNameKey,
) (array.RecordReader, error) {
	bldr := array.NewRecordBuilder(alloc, adbc.GetStatisticNamesSchema)
	defer bldr.Release()

	nameBldr := bldr.Field(0).(*array.StringBuilder)
	keyBldr := bldr.Field(1).(*array.Int16Builder)

	for _, stat := range statistics {
		nameBldr.Append(stat.Name)
		keyBldr.Append(stat.Key)
	}

	rec := bldr.NewRecordBatch()
	defer rec.Release()

	return array.NewRecordReader(adbc.GetStatisticNamesSchema, []arrow.RecordBatch{rec})
}
